create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,role text not null check (role in ('admin','campaign_manager','area_coordinator','volunteer','viewer')),area text,created_at timestamptz default now());
create table if not exists parties (id uuid primary key default gen_random_uuid(),name text not null,short_name text,color text,logo_url text,created_at timestamptz default now());
create table if not exists candidates (id uuid primary key default gen_random_uuid(),party_id uuid references parties(id),full_name text,position text,constituency text,phone text,notes text,created_at timestamptz default now());
create table if not exists voters (id uuid primary key default gen_random_uuid(),full_name text not null,national_id text,phone text,address text,island text,ward text,polling_box text,household_code text,support_status text,priority_level text,assigned_to uuid references profiles(id),last_contacted_at timestamptz,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create unique index if not exists voters_national_id_uq on voters(national_id) where national_id is not null;
create index if not exists voters_phone_idx on voters(phone);
create table if not exists pledges (id uuid primary key default gen_random_uuid(),voter_id uuid references voters(id) on delete cascade,candidate_id uuid references candidates(id),pledge_type text,description text,status text,due_date date,responsible_user uuid references profiles(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists events (id uuid primary key default gen_random_uuid(),title text,event_type text,location text,island text,ward text,start_time timestamptz,end_time timestamptz,expected_attendance integer,actual_attendance integer,assigned_team text,notes text,created_at timestamptz default now());
create table if not exists volunteer_tasks (id uuid primary key default gen_random_uuid(),assigned_to uuid references profiles(id),title text,description text,area text,status text,due_date date,created_at timestamptz default now());
create table if not exists activity_logs (id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id),action text,entity_type text,entity_id uuid,details jsonb,created_at timestamptz default now());
create table if not exists import_logs (id uuid primary key default gen_random_uuid(),file_name text,total_rows integer,created_count integer,updated_count integer,skipped_count integer,errors jsonb,created_at timestamptz default now());
alter table profiles enable row level security; alter table voters enable row level security; alter table pledges enable row level security; alter table events enable row level security; alter table volunteer_tasks enable row level security; alter table parties enable row level security; alter table candidates enable row level security; alter table activity_logs enable row level security; alter table import_logs enable row level security;
create policy read_scoped_voters on voters for select using (auth.uid() is not null);
create policy write_voters_roles on voters for all using (exists(select 1 from profiles p where p.id=auth.uid() and p.role in ('admin','campaign_manager','area_coordinator')));
-- seed
insert into parties (name,short_name,color) values ('Unity Party','UP','#1f77ff') on conflict do nothing;
